Feat/guns shoot system
AgusRambal/SandWar pull request #25
Opened 2023-09-26 22:00 UTC by AgusRambal

## Issue Ticket - Weapons and shoot system

## Cambios
- Agregados los scriptable Objects de las armas, c/u con sus variables y stats
- Utilizados los SO en todas las armas creadas hasta el momento
- Creado el sistema de Disparo en forma de estados
- Agregado el comportamiento de mirar al objetivo de una forma mas suave
- El mismo solo esta aplicado a los marines
- Los enemigos no tiene IA aun

## TODO
- Agregar las animaciones correctas y con sus tiempos correctos
- Agregar VFX de muzzleFlash y sonidos a las armas
- Adaptar los tiempos de entre disparos y recarga a los tiempos de las animaciones
- Ajustar las stats de da;o, tiempos y demas
- Un issue notorio es que la animacion no se reproduce al instante cambiar de estado, hay que solucionar eso

2023-09-26 22:25 UTC, PignataroLucas requested changes

2023-09-26 22:25 UTC, PignataroLucas commented on Assets/Scripts/Core/Battle/CustomLookAtTarget.cs
No entiendo para que se usa esta clase, es para que una unidad cambie de target? Si es asi , deberia estar en una Clase que sea UnitActions y se debe invocar en el estado de "FindNewTarget" o algo por el estilo. Tampoco necesita que sea monobehaviour

2023-09-26 22:25 UTC, PignataroLucas commented on Assets/Scripts/Core/Characters/Insurgent.cs
> +    [SerializeField] private Character insrugent;
Cuidado con el error de tipeo

2023-09-26 22:25 UTC, PignataroLucas commented on Assets/Scripts/Core/GameManager.cs
>      private void CreateMarine(GameObject marine)
Esta funcion es para crear marines desde la base? Si es asi, deberia estar en otro lugar. El marine no deberia poder auto crearse

2023-09-26 22:25 UTC, PignataroLucas commented on Assets/Scripts/StateMachine/States/Shooting.cs
> +            marine.StateMachine.ChangeState(marine.WalkingState);
no se deberian cambiar los estados de la unidad hardcodeando el estado directamente , deberias mandar un evento generico "ChangeState"  para cambiar a walking

2023-09-26 22:25 UTC, PignataroLucas commented on Assets/Scripts/StateMachine/States/Shooting.cs
> +    private void StopShooting()
Lo mismo de arriba, se deberia mandar un evento para cambiar al respectivo estado

2023-09-26 22:25 UTC, PignataroLucas commented on Assets/Scripts/Core/Characters/Marine.cs
> +        CurrentHealth = character.MaxHealth;
Esto deberia ser en un struct de Stats dentro de la clase Marine, ya que si se modifican las variables de vida o accuracy, se va a ver reflejado en el SO

2023-09-26 22:25 UTC, PignataroLucas commented on Assets/Scripts/Core/Characters/Insurgent.cs
> +    public void Damage(float damageAmount)
No estoy encontrando en donde llamas a esta funcion Damage, ya se que es de testeo esto, pero cuidado con llamar a una funcion de en este caso un enemigo, desde otro script ya que rompe con SOLID

2023-09-26 22:27 UTC, PignataroLucas commented
Los SO estan bien, hay que ver de hacer lo que dije antes. Todos los modelos se deben subir aparte del Issue en cuestion, ya que sino se generan un monton de archivos que no tienen nada que ver con la feat.
Depues me hace mucho ruido la SM , tengo miedo que no sea escalable, mas cuando haya que empezar a programar la IA. @santihenry aguardo tu feedback a ver que soluciones podemos sacar.

2023-09-26 22:30 UTC, AgusRambal commented on Assets/Scripts/Core/Characters/Insurgent.cs
> +    [SerializeField] private Character insrugent;
Listo

2023-09-26 22:30 UTC, AgusRambal commented on Assets/Scripts/Core/Battle/CustomLookAtTarget.cs
No, es para que el marine mire al enemigo de una forma suave. Como un lookAt suave

2023-09-26 22:32 UTC, PignataroLucas commented on Assets/Scripts/Core/Battle/CustomLookAtTarget.cs
Ok , entonces esto mismo deberia estar en la clase Marine.

2023-09-26 22:32 UTC, AgusRambal commented on Assets/Scripts/Core/GameManager.cs
>      private void CreateMarine(GameObject marine)
No se esta auto creando, estoy llamando a createMarine desde el gameManager, nada mas

2023-09-26 22:33 UTC, AgusRambal commented on Assets/Scripts/Core/GameManager.cs
>      private void CreateMarine(GameObject marine)
O sea compro un marine y despues lo creo, pero no se autcrea

2023-09-26 22:33 UTC, PignataroLucas commented on Assets/Scripts/Core/GameManager.cs
>      private void CreateMarine(GameObject marine)
Claro, pero por eso. Hay una funcion que se llama "CreateMarine" que crea un marine dentro de Marine. El GameManager deberia encargarse de esto. o algun otro Manager

2023-09-26 22:34 UTC, AgusRambal commented on Assets/Scripts/Core/GameManager.cs
>      private void CreateMarine(GameObject marine)
No encuentro donde ves create marine dentro de marine

2023-09-26 22:35 UTC, AgusRambal commented on Assets/Scripts/Core/GameManager.cs
>      private void CreateMarine(GameObject marine)
Una es reclutar, donde lo compras y cuando lo compras, lo creas, pero esta separado uno de otro, y todo desde el game manager

2023-09-26 22:37 UTC, AgusRambal commented on Assets/Scripts/Core/Characters/Insurgent.cs
> +    public void Damage(float damageAmount)
Tenes razon me olvide de llamar damage, la iba a llamar cuando el arma disparo, y pego en un enemigo, ahi se llama a damage, puedo hacerlo asi o enviar un evento

2023-09-26 22:38 UTC, PignataroLucas commented on Assets/Scripts/Core/GameManager.cs
>      private void CreateMarine(GameObject marine)
Ah ya se que paso, 
![image](https://github.com/AgusRambal/SandWar/assets/91335382/40f52fdc-2143-4a05-91c1-8e61582a053b)
estaba scrolleando y no vi que paso a otro script. pasa que justo arriba tenia Marine no vi que saltaba a GameManager. Esta perfecto doy resuelto la conversacion

2023-09-26 22:38 UTC, AgusRambal commented on Assets/Scripts/Core/Characters/Insurgent.cs
> +    public void Damage(float damageAmount)
![image](https://github.com/AgusRambal/SandWar/assets/73607427/7f1d909e-9b8b-4c2f-acd4-b1aa554052d5)

2023-09-26 22:41 UTC, PignataroLucas commented on Assets/Scripts/Core/Characters/Insurgent.cs
> +    public void Damage(float damageAmount)
Lo correcto seria hacer como te puse antes. Mandas un evento que le estas haciendo da;o , el enemigo recibe ese evento y se descuenta la respectiva vida.

2023-09-26 22:43 UTC, AgusRambal commented on Assets/Scripts/Core/Battle/CustomLookAtTarget.cs
Listo, ya lo pase a la clase Marine

2023-09-26 22:48 UTC, AgusRambal commented on Assets/Scripts/Core/Characters/Insurgent.cs
> +    public void Damage(float damageAmount)
![image](https://github.com/AgusRambal/SandWar/assets/73607427/954469ad-3b62-417f-836a-45ef5dbcd9c3)

Listo

2023-09-26 22:55 UTC, PignataroLucas commented on Assets/Scripts/Core/Battle/CustomLookAtTarget.cs
Bien, por mi ya esta. Aguardo a feedback de santi para Resolve Conversation

2023-09-26 22:56 UTC, PignataroLucas commented on Assets/Scripts/Core/Characters/Insurgent.cs
> +    public void Damage(float damageAmount)
Bien, por mi ya esta. Aguardo a feedback de santi para Resolve Conversation

2023-09-26 22:59 UTC, AgusRambal commented on Assets/Scripts/Core/Characters/Marine.cs
> +        CurrentHealth = character.MaxHealth;
![image](https://github.com/AgusRambal/SandWar/assets/73607427/bd8b5f8e-c37a-4167-b67c-4ec52d1c11a2)

Listo el struct en la clase marine

2023-09-26 23:03 UTC, PignataroLucas commented on Assets/Scripts/Core/Characters/Marine.cs
> +        CurrentHealth = character.MaxHealth;
La forma correcta seria Public float Life/Health . Una variable Privada private States _stats y en el start haces : 
_stats = new Stats()
{
    Life/Health = characther.Life/Health
}

2023-09-27 00:37 UTC, AgusRambal commented on Assets/Scripts/Core/Characters/Marine.cs
> +        CurrentHealth = character.MaxHealth;
![image](https://github.com/AgusRambal/SandWar/assets/73607427/8af03404-6224-404c-bfc5-569828dac5ba)
 Listo el struct

2023-09-27 01:57 UTC, santihenry commented
Esta todo ok, lo único como dijo lucas y vi que hablaron en ds, hay que comitear los assets a parte, porque se vuelve un quilombo revisar el los commits con todos los archivos que genera subir assets y la creacion de prefabs.

2023-09-27 01:58 UTC, santihenry commented on Assets/Scripts/StateMachine/States/Shooting.cs
> +            marine.StateMachine.ChangeState(marine.WalkingState);
Con respecto a esto si, seria mejor Usar eventos, pero tendría que revisar la implementación de la FSM de momento no  veo mal que se cambie de esta manera ya que parece ser la forma en la que trabaja esta fsm

2023-09-27 01:59 UTC, santihenry approved these changes

2023-09-27 02:00 UTC, AgusRambal commented on Assets/Scripts/StateMachine/States/Shooting.cs
> +            marine.StateMachine.ChangeState(marine.WalkingState);
Claro, eso pensaba yo, esta funciona así parece, pero si les parece mejor una FSM mas genérica con eventos y todo, podemos poner una Issue nueva y cambiarla, por mi no Problem

2023-09-27 10:49 UTC, PignataroLucas approved these changes
Aprobado, quedamos en ver la implementacion de la fsm, me gustaria ver el video en que se baso agus . Tratemos de no tocar los scripts core de Marine y los estados por si hay que hacer una refactorizacion

2023-09-27 11:55 UTC, merged